services:
  - type: web
    name: safepasto-backend
    env: docker
    dockerfilePath: ./dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: safepasto-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: FRONTEND_URL
        value: https://frontend-safepasto-vcbw.vercel.app
      - key: CORS_ALLOWED_ORIGIN_PATTERNS
        value: https://*.vercel.app
      - key: WS_ALLOWED_ORIGIN_PATTERNS
        value: https://*.vercel.app
    healthCheckPath: /api/health

databases:
  - name: safepasto-db
    databaseName: safepasto_db
    user: safepasto_user
    plan: free
